name: "Publish to AMO"
on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: ${{ github.workspace }}
          channel: listed

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ${{ github.workspace }}

      - name: "web-ext build upload"
        id: web-ext-build-upload
        uses: actions/upload-artifact@v4
        with:
          name: build-upload
          path: ${{ github.workspace }}/web-ext-artifacts/*.zip
          
      - name: "Get manifest version"
        id: get_version
        run: |
          VERSION=$(jq -r '.version' ${{ github.workspace }}/manifest.json)
          echo "Version: $VERSION"
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: "Collect sources"
        run: git archive --format=zip --output=sources.zip ${{ github.ref }}

  publish_amo:
    name: Publish to AMO
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "web-ext build download"
        id: web-ext-build-download
        uses: actions/download-artifact@v4
        with:
          name: build-upload

      - name: "web-ext sign AMO"
        id: web-ext-sign-amo
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ github.workspace }}/web-ext-artifacts./*.zip
        
          channel: listed
  
          approvalNotes: "Please find more information at https://github.com/chaara-dev/Dracula-News/releases"
          releaseNotes: ${{ github.event.release.body }}
  
          apiKey: ${{ secrets.FIREFOX_JWT_ISSUER }}
          apiSecret: ${{ secrets.FIREFOX_JWT_SECRET }}
          timeout: 900000

  publish_xpi:
    name: Publish as XPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "web-ext build download"
        id: web-ext-build-download
        uses: actions/download-artifact@v4
        with:
          name: build-upload

      - name: "web-ext sign XPI"
        id: web-ext-sign-xpi
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ github.workspace }}/web-ext-artifacts/*.zip
        
          channel: unlisted
  
          approvalNotes: "Please find more information at https://github.com/chaara-dev/Dracula-News/releases"
          releaseNotes: ${{ github.event.release.body }}
  
          apiKey: ${{ secrets.FIREFOX_JWT_ISSUER }}
          apiSecret: ${{ secrets.FIREFOX_JWT_SECRET }}
          timeout: 900000

