name: "Build and Publish"
on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_version.outputs.release_version }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: ${{ github.workspace }}
          channel: listed

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ${{ github.workspace }}
          filename: "dracula_news-{version}.zip"

      - name: "Upload Built Artifact"
        id: web-ext-build-upload
        uses: actions/upload-artifact@v4
        with:
          name: built-addon
          path: ${{ steps.web-ext-build.outputs.target }}
          
      - name: "Get manifest version"
        id: get_version
        run: |
          VERSION=$(jq -r '.version' ${{ github.workspace }}/manifest.json)
          echo "Version: $VERSION"
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: "Collect sources"
        run: git archive --format=zip --output=sources.zip ${{ github.ref }}

  publish_amo:
    name: Publish to AMO
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "web-ext build download"
        id: web-ext-build-download
        uses: actions/download-artifact@v4
        with:
          name: built-addon
          path: ${{ github.workspace }}

      - name: "Show Downloaded Files"
        run: ls -R ${{ steps.web-ext-build-download.outputs.download-path }}

      - name: "web-ext sign AMO"
        id: web-ext-sign-amo
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build-download.outputs.download-path }}/*.zip
        
          channel: listed
  
          approvalNotes: "Please find more information at https://github.com/chaara-dev/Dracula-News/releases"
          releaseNotes: ${{ github.event.release.body }}
  
          apiKey: ${{ secrets.FIREFOX_JWT_ISSUER }}
          apiSecret: ${{ secrets.FIREFOX_JWT_SECRET }}
          timeout: 900000

  publish_xpi:
    name: Publish as XPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "web-ext build download"
        id: web-ext-build-download
        uses: actions/download-artifact@v4
        with:
          name: built-addon
          path: ${{ github.workspace }}

      - name: "Show Download Path"
        run: echo ${{ steps.web-ext-build-download.outputs.download-path }}

      - name: "Show All Files"
        run: ls -R

      - name: "web-ext sign XPI"
        id: web-ext-sign-xpi
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ github.workspace }}/built-addon/dracula_news-${{ needs.build.outputs.release-version }}.zip
        
          channel: unlisted
  
          approvalNotes: "Please find more information at https://github.com/chaara-dev/Dracula-News/releases"
          releaseNotes: ${{ github.event.release.body }}
  
          apiKey: ${{ secrets.FIREFOX_JWT_ISSUER }}
          apiSecret: ${{ secrets.FIREFOX_JWT_SECRET }}
          timeout: 900000

      - name: "Attach release assets to release"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            ${{ steps.web-ext-sign-xpi.outputs.target }}
